server:
  port: 8081

spring:
  application:
    name: workload-service
  data:
    mongodb:
      uri: ${MONGODB_URI}
  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL}
    user: ${ACTIVEMQ_USER}
    password: ${ACTIVEMQ_PASSWORD}

jms:
  queue:
    trainer-workload: trainer.workload.queue
  listener:
    concurrency: "3-10"

springdoc:
  swagger-ui:
    url: /trainer-workload-service-api.yml
    path: /swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: ${JWT_SECRET}