server:
  port: 8765

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true
          httpclient:
            response-timeout: 5s
            connect-timeout: 3000

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
    instances:
      gca-core-service:
        baseConfig: default
      workload-service:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: ${JWT_SECRET}
