name: CI - Build, Test and SonarCloud for gca core service

on:
  push:
    branches: [ develop ]
    paths:
      - 'gca-core-service/**'
      - 'workload-service/**'
  pull_request:
    branches: [ develop ]
    paths:
      - 'gca-core-service/**'
      - 'workload-service/**'

jobs:
  build:
    name: Build and run tests with SonarCloud review for gca-core-service
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: gca-core-service


    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Microservice 1
      - name: Build, test and analyze gca-core-service
        working-directory: ./gca-core-service
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
            -Dsonar.qualitygate.wait=true \
            -Dsonar.coverage.exclusions=**/mapper/**,**/openapi/**,**/dto/**,**/model/**,**/web/**,**/config/**

      # Microservice 2
      - name: Build and analyze workload-service
        working-directory: ./workload-service
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
            -Dsonar.qualitygate.wait=true \
            -Dsonar.coverage.exclusions=**/mapper/**,**/openapi/**,**/dto/**,**/model/**,**/web/**,**/config/**